# Generated by Django 5.1.1 on 2024-10-03 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Area')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Nome do Projeto')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data do Projeto')),
                ('descricao', models.CharField(blank=True, help_text='Maximo de caracteres são 500', max_length=500, verbose_name='Descrição')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link')),
                ('python', models.BooleanField(blank=True, default=False)),
                ('java', models.BooleanField(blank=True, default=False)),
                ('css', models.BooleanField(blank=True, default=False)),
                ('html', models.BooleanField(blank=True, default=False)),
                ('javascript', models.BooleanField(blank=True, default=False)),
                ('c', models.BooleanField(blank=True, default=False)),
                ('nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='app_nome', to='App.nome', verbose_name='Área')),
            ],
        ),
    ]
